---
title: "p8105_hw3_yl4924"
author: "Yongzheng Li"
date: "2022-10-15"
output: github_document
---

# Load the package adjust graph display
```{r, message=FALSE,warning=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

# Problem 2

### load, clean and tidy the data
```{r}
accel_data <- read_csv(
              "./data/accel_data.csv") %>% 
              janitor::clean_names() %>% 
              pivot_longer(
                starts_with("activity"),
                names_to = "minute",
                names_prefix = "activity_",
                values_to = "activity_count") %>% 
              mutate(
                minute = as.integer(minute),
                weekend = case_when(
                  day %in% c("Saturday", "Sunday")                                   ~ 1,
                  day %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday") ~ 0))
                 
                
                
              
```


